# Generated by Django 4.0.5 on 2022-09-13 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='preference',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('preferences', models.ManyToManyField(to='api.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
